import NavBar from "@/components/navbar";
import { ThemeProvider } from "@/components/theme-provider";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const NeueMontreal = localFont({
  src: [
    {
      path: "../../public/fonts/NeueMontreal/NeueMontreal-Light.otf",
      weight: "200",
      style: "normal",
    },
    {
      path: "../../public/fonts/NeueMontreal/NeueMontreal-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/NeueMontreal/NeueMontreal-Medium.otf",
      weight: "1000",
      style: "normal",
    },
    {
      path: "../../public/fonts/NeueMontreal/NeueMontreal-Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/NeueMontreal/NeueMontreal-LightItalic.otf",
      weight: "200",
      style: "italic",
    },
    {
      path: "../../public/fonts/NeueMontreal/NeueMontreal-Italic.otf",
      weight: "400",
      style: "italic",
    },
    {
      path: "../../public/fonts/NeueMontreal/NeueMontreal-MediumItalic.otf",
      weight: "1000",
      style: "italic",
    },
    {
      path: "../../public/fonts/NeueMontreal/NeueMontreal-BoldItalic.otf",
      weight: "700",
      style: "italic",
    },
  ],

  variable: "--font-NeueMontreal",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${NeueMontreal.variable}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NavBar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
